name: Compile Linux Kernel

on:
  #schedule:
    #- cron: '0 0 * * *'  # 每天的UTC时间0点触发，可以根据需要调整时间
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Clone torvalds/linux repository
      run: |
        git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        cd linux
        git checkout v6.6.71

    - name: Set up build dependencies
      run: |
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc dwarves fakeroot libncurses5

    - name: Configure kernel
      run: |
        cd linux
        make defconfig  # 使用默认配置文件

    - name: Build kernel
      run: |
        cd linux
        make -j$(nproc) deb-pkg
        
    - name: Upload kernel deb packages
      uses: actions/upload-artifact@v3
      with:
        name: kernel-packages
        path: ${{ github.workspace }}/../linux-*.deb
