name: Compile Linux Kernel

on:
  push:
    branches:
      - master  # 或者你想要监控的其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

    - name: Configure kernel
      run: |
        make defconfig  # 或者使用你自己的配置文件
        make menuconfig # 可选步骤，如果需要修改配置

    - name: Build kernel
      run: |
        make -j$(nproc)

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-build
        path: |
          arch/x86/boot/bzImage
          System.map
          vmlinux
