name: Compile Linux Kernel

on:
  #schedule:
    #- cron: '0 0 * * *'  # 每天的UTC时间0点触发，可以根据需要调整时间
  #push:
    #branches:
      #- main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Clone torvalds/linux repository
      run: |
        git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        cd linux
        git checkout v6.6.71

    - name: Set up build dependencies
      run: |
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev debhelper dh-virtualenv bc kmod cpio liblz4-tool rsync

    - name: Configure kernel
      run: |
        cd linux
        yes "" | make oldconfig  # 使用默认配置并自动接受所有默认值
        scripts/config --enable MODULES  # 启用模块支持
        scripts/config --enable MODULE_COMPRESS  # 启用模块压缩
        scripts/config --enable MODULE_COMPRESS_XZ  # 使用XZ压缩模块

    - name: Build kernel
      run: |
        cd linux
        make KBUILD_CFLAGS="-S" -j$(nproc)
        ls
        
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel
        path: |
          ./**/*.s
