name: Compile Linux Kernel

on:
  #schedule:
    #- cron: '0 0 * * *'  # 每天的UTC时间0点触发，可以根据需要调整时间
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Clone torvalds/linux repository
      run: |
        git clone https://github.com/torvalds/linux.git
        cd linux

    - name: Set up build dependencies
      run: |
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

    - name: Configure kernel
      run: |
        cd linux
        make defconfig  # 使用默认配置文件

    - name: Build kernel
      run: |
        cd linux
        make -j$(nproc)

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-build
        path: |
          linux/arch/x86/boot/bzImage
          linux/System.map
          linux/vmlinux
