name: Compile Linux Kernel BBR V3

on:
  #schedule:
    #- cron: '0 0 * * *'  # 每天的UTC时间0点触发，可以根据需要调整时间
  #push:
    #branches:
      #- main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Clone torvalds/linux repository and download bbr
      run: |
        git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        cd linux
        git checkout linux-6.12.y
        cd net/ipv4
        rm tcp_bbr.c
        wget https://raw.githubusercontent.com/google/bbr/refs/heads/v3/net/ipv4/tcp_bbr.c

    - name: Set up build dependencies
      run: |
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev debhelper dh-virtualenv

    - name: Configure kernel
      run: |
        cd linux
        make defconfig  # 使用默认配置文件

    - name: Build kernel
      run: |
        cd linux
        make -j$(nproc) bindeb-pkg

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-deb
        path: |
          linux-*.deb
